title: homebrew-hep
description: Homebrew's package index

repo: homebrew-hep
remote: https://github.com/davidchall/homebrew-hep

remote_theme: Homebrew/brew.sh@ea364121ad92b0a1a5d89e033f9bb5773c7777ea

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - script
  - Gemfile*
  - vendor
  - README.md

logo: https://raw.githubusercontent.com/davidchall/homebrew-hep/HEAD/.github/homebrew-hep-logo.png
